### ISSUE TITLE
Missing units...

### ISSUE THREAD

**Issue by MichalRAD** [ConroyBadger/DelphiKinect2Depth#1]
...BmpUtils, Routines... It is not necessary, but for smooth project compile yes. Can you add them?

**Comment by ConroyBadger** [comment]
Hi Michal. Sorry I guess I missed those - I've added them now :)

https://github.com/ConroyBadger/DelphiKinect2Depth

**Comment by MichalRAD** [comment]
It will also work with Kinect2?

**Comment by ConroyBadger** [comment]
Yes it works only with Kinect2. I have code for the older Kinects as well
but they are no longer available and the Kinect2 is better all around.

**Comment by MichalRAD** [comment]
Hmm. I tested it and does not work. Kinect II is ok (i test it on MS Kinect SDK), 
![image](https://cloud.githubusercontent.com/assets/24889863/23294984/8520bff8-fa6e-11e6-968e-b2428af4414b.png)
After i press OK...
![image](https://cloud.githubusercontent.com/assets/24889863/23294995/958b6e6a-fa6e-11e6-91c8-c9c567b486b4.png)
DLL is in the same folder as application exe file..

**Comment by MichalRAD** [comment]
Sorry, it works after install Visual Studio runtime redistributable.. :)
